from ComfyUI_Mokkaboss1.nodes import *

NODE_CLASS_MAPPINGS = {
    "DoubleClipTextEncode": DoubleClipTextEncode,
    "HashText": HashText,
    "IndoorBackgrounds": IndoorBackgrounds,   
    "LandscapeBackgrounds": LandscapeBackgrounds,
    "OptimalCrop": OptimalCrop,
    "X_In_a_Dress": X_In_a_Dress,
    "X_In_a_Suit": X_In_a_Suit,
    "WrapText": WrapText,
    "AspectRatioCondition": AspectRatioCondition,
    "SDXLEmptyLatent": SDXLEmptyLatent,
    "ZoomCrop": ZoomCrop,
    "IntFloatDict": IntFloatDict,
    "WorkflowSettings": WorkflowSettings,
    "IntStringDict": IntStringDict,
    "ConnectImage": ConnectImage,
    "ConnectInteger": ConnectInteger,
    "ConnectString": ConnectString,
    "ConnectFloat": ConnectFloat,
    "ConnectLatent": ConnectLatent,
    "TimeStamp": TimeStamp,
    "SaveWithMetaData": SaveWithMetaData,
    "TricolorComposition": TricolorComposition,
    "Colors": Colors,
    "HueSatLum": HueSatLum,
    "EmbeddingLoader": EmbeddingLoader,
    "ImageDimensions": ImageDimensions,
    "SimplePrompts": SimplePrompts,
    "IntEvaluate": IntEvaluate,
    "ImageResizeLong": ImageResizeLong,
    "PhotomontageA": PhotomontageA,
    "PhotomontageB": PhotomontageB,
    "PhotomontageC": PhotomontageC,
    
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "DoubleClipTextEncode": "👑 DoubleClipTextEncode",
    "HashText": "👑 HashText",
    "IndoorBackgrounds": "👑 IndoorBackgrounds",
    "LandscapeBackgrounds": "👑 LandscapeBackgrounds",
    "OptimalCrop": "👑 OptimalCrop",
    "X_In_a_Dress": "👑 X_In_a_Dress",
    "X_In_a_Suit": "👑 X_In_a_Suit",
    "WrapText": "👑 WrapText",
    "AspectRatioCondition": "👑 AspectRatioCondition",
    "SDXLEmptyLatent": "👑 SDXLEmptyLatent",
    "ZoomCrop": "👑 ZoomCrop",
    "IntFloatDict": "👑 IntFloatDict",
    "WorkflowSettings": "👑 WorkflowSettings",
    "IntStringDict": "👑 IntStringDict",
    "ConnectImage": "👑 ConnectImage",
    "ConnectInteger": "👑 ConnectInteger",
    "ConnectString": "👑 ConnectString",
    "ConnectFloat": "👑 ConnectFloat",
    "ConnectLatent": "👑 ConnectLatent",
    "TimeStamp": "👑 TimeStamp",
    "SaveWithMetaData": "👑 SaveWithMetaData",
    "TricolorComposition": "👑 TricolorComposition",
    "Colors":"👑 Colors",
    "HueSatLum": "👑 HueSatLum",
    "EmbeddingLoader": "👑 EmbeddingLoader",
    "ImageDimensions": "👑 ImageDimensions",
    "SimplePrompts": "👑 SimplePrompts",
    "IntEvaluate": "👑 IntEvaluate",
    "ImageResizeLong": "👑 ImageResizeLong",
    "PhotomontageA": "👑 PhotomontageA",
    "PhotomontageB": "👑 PhotomontageB",
    "PhotomontageC": "👑 PhotomontageC",
}
print ("👑 Mokkaboss1 32 Custom Nodes: Loaded")
